[package]
name = "bevy2d"
version = "0.1.0"
authors = ["Shane Lillie <ignignokterr@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
bevy_prototype_lyon = "0.3"
bevy_rapier2d = { version = "0.9", features = [ "simd-stable", "parallel", "serde-serialize" ] }
once_cell = "1.7"

[dependencies.core_lib]
path = "../core"
